version: "3.9"
services:
  market-app:
    build: .
    ports:
      - "3000:3000"
    links:
      - market-db
  market-db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - mysql-data:/var/lib/mysql
      # mongo -> /data/db
      # postgres -> /var/lib/postgresql/data
volumes:
  mysql-data:
